package com.example.moviesapp.core

const val BASE_URL = "https://api.themoviedb.org/3/"
const val AUTHORIZATION_BEARER_TOKEN = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5N2U5NTczZjY1MWZiNjA1NTY0ZjUzZjkyMDA0ZTQ0MiIsIm5iZiI6MTc3MjM1ODQxNy4xMDQsInN1YiI6IjY5YTQwYjExMzFiNWVlNGJlNmUyYjU3MiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.GCxsgj9BCwG0TCTw1b_M51jkSCAuAZJFoeWDMVpxxvg"